### ISSUE TITLE
Clicking MUN directs to homepage, but since it's the homepage, we don't want anything in URL except domain name

### ISSUE THREAD

**Issue by Awesome-E** [tesoro-cs/tesoro-mun#5]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/54484616/157588734-3aedab69-b13a-4dff-92f8-a7e715de96a7.png">

The URL should be `https://mun.thsclub.org/`, not `https://mun.thsclub.org/index.html`.

This might be a result of developing and opening files directly – please don't do that. The least you can do is use the Live Server Extension in VSCode.

**Comment by josephgeis** [comment]
The `href` attribute should just be set to `/` in the links.
